# Generated by Django 3.1.5 on 2021-02-01 15:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210201_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
