# Generated by Django 3.0.5 on 2021-02-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='code',
            new_name='web_code',
        ),
    ]
