# Generated by Django 3.1.5 on 2021-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='naira-sign2.jpg', height_field='height_field', upload_to='profile_pics', width_field='width_field'),
        ),
    ]
