# Generated by Django 3.0.5 on 2021-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210208_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='unique_tag'),
        ),
    ]
