# Generated by Django 3.1.5 on 2021-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name_plural': 'Customer Info'},
        ),
    ]
