# Generated by Django 3.1.5 on 2021-01-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0002_auto_20210122_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
