# Generated by Django 3.1.7 on 2021-04-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20210402_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
